export type Airport = {
  iata: string
  name: string
  country: string
  timeZone: string
  latitude: number
  longitude: number
}

export type RyanairAirport = {
  name: string
  country: string
  timeZone: string
  latitude: string
  longitude: string
}

export type EasyJetAirport = {
  name: string
  country: string
  flagUrl: string
  countryCode: string
  latitude: number
  longitude: number
}

// taken from https://www.ryanair.com/api/booking/v4/en-gb/res/stations

export const _ryanairAirports: Record<string, RyanairAirport> = {
  AAL: {
    name: "Aalborg",
    country: "DK",
    timeZone: "DK",
    latitude: "570534N",
    longitude: "0095057E",
  },
  AAR: {
    name: "Aarhus",
    country: "DK",
    timeZone: "DK",
    latitude: "561814N",
    longitude: "0103710E",
  },
  ABZ: {
    name: "Aberdeen",
    country: "GB",
    timeZone: "GB",
    latitude: "571215N",
    longitude: "0021201W",
  },
  ACE: {
    name: "Lanzarote",
    country: "ES",
    timeZone: "ES2",
    latitude: "285644N",
    longitude: "0133619W",
  },
  ADB: {
    name: "Adnan Menderes",
    country: "TR",
    timeZone: "TR",
    latitude: "381733N",
    longitude: "0270925E",
  },
  AGA: {
    name: "Agadir",
    country: "MA",
    timeZone: "MA",
    latitude: "301930N",
    longitude: "0092447W",
  },
  AGH: {
    name: "Angelholm",
    country: "SE",
    timeZone: "SE",
    latitude: "561746N",
    longitude: "0125050E",
  },
  AGP: {
    name: "Malaga",
    country: "ES",
    timeZone: "ES1",
    latitude: "364030N",
    longitude: "0042957W",
  },
  AHO: {
    name: "Alghero",
    country: "IT",
    timeZone: "IT",
    latitude: "403749N",
    longitude: "0081723E",
  },
  ALC: {
    name: "Alicante",
    country: "ES",
    timeZone: "ES1",
    latitude: "381656N",
    longitude: "0003329W",
  },
  AMM: {
    name: "Amman",
    country: "JO",
    timeZone: "JO",
    latitude: "314300N",
    longitude: "0360000E",
  },
  AMS: {
    name: "Amsterdam",
    country: "NL",
    timeZone: "NL",
    latitude: "521829N",
    longitude: "0044551E",
  },
  ANG: {
    name: "Angoulême",
    country: "FR",
    timeZone: "FR",
    latitude: "454346N",
    longitude: "0001309E",
  },
  AOC: {
    name: "Altenburg",
    country: "DE",
    timeZone: "DE",
    latitude: "505855N",
    longitude: "0123023E",
  },
  AOI: {
    name: "Ancona",
    country: "IT",
    timeZone: "IT",
    latitude: "433700N",
    longitude: "0132137E",
  },
  AQJ: {
    name: "Aqaba",
    country: "JO",
    timeZone: "JO",
    latitude: "293642N",
    longitude: "0350105E",
  },
  ARN: {
    name: "Arlanda",
    country: "SE",
    timeZone: "SE",
    latitude: "593907N",
    longitude: "0175507E",
  },
  ARW: {
    name: "Arad",
    country: "RO",
    timeZone: "RO",
    latitude: "461036N",
    longitude: "0211543E",
  },
  ATH: {
    name: "Athens",
    country: "GR",
    timeZone: "GR",
    latitude: "375611N",
    longitude: "0235640E",
  },
  AXD: {
    name: "Alexandropoulis",
    country: "GR",
    timeZone: "GR",
    latitude: "405121N",
    longitude: "0255723E",
  },
  AYT: {
    name: "Antalya",
    country: "TR",
    timeZone: "TR",
    latitude: "365355N",
    longitude: "0304802E",
  },
  BBU: {
    name: "Baneasa",
    country: "RO",
    timeZone: "RO",
    latitude: "443012N",
    longitude: "0260608E",
  },
  BCN: {
    name: "Barcelona ",
    country: "ES",
    timeZone: "ES1",
    latitude: "411749N",
    longitude: "0020442E",
  },
  BDS: {
    name: "Brindisi",
    country: "IT",
    timeZone: "IT",
    latitude: "403938N",
    longitude: "0175653E",
  },
  BEG: {
    name: "Belgrad Airport",
    country: "RS",
    timeZone: "RS",
    latitude: "444906N",
    longitude: "0201833E",
  },
  BEM: {
    name: "Beni Mellal Airport",
    country: "MA",
    timeZone: "MA",
    latitude: "322022N",
    longitude: "0062139W",
  },
  BER: {
    name: "Berlin (Brandenburg)",
    country: "DE",
    timeZone: "DE",
    latitude: "522200N",
    longitude: "0133012E",
  },
  BES: {
    name: "Brest",
    country: "FR",
    timeZone: "FR",
    latitude: "482650N",
    longitude: "0042518W",
  },
  BEY: {
    name: "Beirut International",
    country: "LB",
    timeZone: "LB",
    latitude: "334846N",
    longitude: "0352925E",
  },
  BFS: {
    name: "Belfast",
    country: "GB",
    timeZone: "GB",
    latitude: "543927N",
    longitude: "0061257W",
  },
  BGO: {
    name: "Flesland Airport",
    country: "NO",
    timeZone: "NO",
    latitude: "601737N",
    longitude: "0051310E",
  },
  BGY: {
    name: "Milan (Bergamo)",
    country: "IT",
    timeZone: "IT",
    latitude: "454008N",
    longitude: "0094201E",
  },
  BHD: {
    name: "Belfast (City)",
    country: "GB",
    timeZone: "GB",
    latitude: "543705N",
    longitude: "0055221W",
  },
  BHX: {
    name: "Birmingham",
    country: "GB",
    timeZone: "GB",
    latitude: "522713N",
    longitude: "0014452W",
  },
  BIA: {
    name: "Bastia Poretta",
    country: "FR",
    timeZone: "FR",
    latitude: "423257N",
    longitude: "0092910E",
  },
  BIO: {
    name: "Bilbao",
    country: "ES",
    timeZone: "ES1",
    latitude: "431804N",
    longitude: "0025438W",
  },
  BIQ: {
    name: "Biarritz",
    country: "FR",
    timeZone: "FR",
    latitude: "432806N",
    longitude: "0013152W",
  },
  BJV: {
    name: "Milas-Bodrum",
    country: "TR",
    timeZone: "TR",
    latitude: "371502N",
    longitude: "0273952E",
  },
  BLK: {
    name: "Blackpool",
    country: "GB",
    timeZone: "GB",
    latitude: "534617N",
    longitude: "0030142W",
  },
  BLL: {
    name: "Billund",
    country: "DK",
    timeZone: "DK",
    latitude: "554425N",
    longitude: "0090906E",
  },
  BLQ: {
    name: "Bologna",
    country: "IT",
    timeZone: "IT",
    latitude: "443151N",
    longitude: "0111749E",
  },
  BNX: {
    name: "Banja Luka",
    country: "BA",
    timeZone: "BA",
    latitude: "445600N",
    longitude: "0171800E",
  },
  BOD: {
    name: "Bordeaux",
    country: "FR",
    timeZone: "FR",
    latitude: "444943N",
    longitude: "0004255W",
  },
  BOH: {
    name: "Bournemouth",
    country: "GB",
    timeZone: "GB",
    latitude: "504648N",
    longitude: "0015033W",
  },
  BOJ: {
    name: "Burgas",
    country: "BG",
    timeZone: "BG",
    latitude: "423411N",
    longitude: "0273055E",
  },
  BRE: {
    name: "Bremen",
    country: "DE",
    timeZone: "DE",
    latitude: "530251N",
    longitude: "0084712E",
  },
  BRI: {
    name: "Bari",
    country: "IT",
    timeZone: "IT",
    latitude: "410817N",
    longitude: "0164554E",
  },
  BRQ: {
    name: "Brno",
    country: "CZ",
    timeZone: "CZ",
    latitude: "490905N",
    longitude: "0164140E",
  },
  BRS: {
    name: "Bristol",
    country: "GB",
    timeZone: "GB",
    latitude: "512257N",
    longitude: "0024308W",
  },
  BRU: {
    name: "Brussels (Zaventem)",
    country: "BE",
    timeZone: "BE",
    latitude: "505405N",
    longitude: "0042904E",
  },
  BSL: {
    name: "Basel",
    country: "CH",
    timeZone: "CH",
    latitude: "473604N",
    longitude: "0073118E",
  },
  BTS: {
    name: "Bratislava",
    country: "SK",
    timeZone: "SK",
    latitude: "481000N",
    longitude: "0171300E",
  },
  BUD: {
    name: "Budapest ",
    country: "HU",
    timeZone: "HU",
    latitude: "472613N",
    longitude: "0191520E",
  },
  BVA: {
    name: "Paris (Beauvais)",
    country: "FR",
    timeZone: "FR",
    latitude: "492716N",
    longitude: "0020646E",
  },
  BVE: {
    name: "Brive (Souillac)",
    country: "FR",
    timeZone: "FR",
    latitude: "450906N",
    longitude: "0012819E",
  },
  BZG: {
    name: "Bydgoszcz",
    country: "PL",
    timeZone: "PL",
    latitude: "530548N",
    longitude: "0175840E",
  },
  BZR: {
    name: "Beziers",
    country: "FR",
    timeZone: "FR",
    latitude: "431924N",
    longitude: "0032112E",
  },
  CAG: {
    name: "Cagliari",
    country: "IT",
    timeZone: "IT",
    latitude: "391505N",
    longitude: "0090328E",
  },
  CCF: {
    name: "Carcassonne",
    country: "FR",
    timeZone: "FR",
    latitude: "431257N",
    longitude: "0021831E",
  },
  CDG: {
    name: "Charles De Gaulle Airport",
    country: "FR",
    timeZone: "FR",
    latitude: "490035N",
    longitude: "0023252E",
  },
  CDT: {
    name: "Castellon",
    country: "ES",
    timeZone: "ES1",
    latitude: "401251N",
    longitude: "0000424E",
  },
  CFE: {
    name: "Clermont (Ferrand)",
    country: "FR",
    timeZone: "FR",
    latitude: "454709N",
    longitude: "0030945E",
  },
  CFU: {
    name: "Corfu",
    country: "GR",
    timeZone: "GR",
    latitude: "393607N",
    longitude: "0195442E",
  },
  CGN: {
    name: "Cologne (Bonn)",
    country: "DE",
    timeZone: "DE",
    latitude: "505157N",
    longitude: "0070834E",
  },
  CHQ: {
    name: "Crete (Chania)",
    country: "GR",
    timeZone: "GR",
    latitude: "353154N",
    longitude: "0240859E",
  },
  CIA: {
    name: "Rome (Ciampino)",
    country: "IT",
    timeZone: "IT",
    latitude: "414756N",
    longitude: "0123542E",
  },
  CIY: {
    name: "Comiso",
    country: "IT",
    timeZone: "IT",
    latitude: "365941N",
    longitude: "0143625E",
  },
  CLJ: {
    name: "Cluj",
    country: "RO",
    timeZone: "RO",
    latitude: "464707N",
    longitude: "0234110E",
  },
  CMN: {
    name: "Mohamed V Airport",
    country: "MA",
    timeZone: "MA",
    latitude: "332203N",
    longitude: "0073524W",
  },
  CND: {
    name: "Constanta",
    country: "RO",
    timeZone: "RO",
    latitude: "442100N",
    longitude: "0282900E",
  },
  CPH: {
    name: "Copenhagen ",
    country: "DK",
    timeZone: "DK",
    latitude: "553713N",
    longitude: "0123901E",
  },
  CQM: {
    name: "Ciudad Real",
    country: "ES",
    timeZone: "ES1",
    latitude: "385126N",
    longitude: "0035817W",
  },
  CRA: {
    name: "Craiova",
    country: "RO",
    timeZone: "RO",
    latitude: "441905N",
    longitude: "0235319E",
  },
  CRL: {
    name: "Brussels (Charleroi)",
    country: "BE",
    timeZone: "BE",
    latitude: "502733N",
    longitude: "0042714E",
  },
  CRV: {
    name: "Crotone",
    country: "IT",
    timeZone: "IT",
    latitude: "385957N",
    longitude: "0170447E",
  },
  CSO: {
    name: "Magdeburg (Cochstedt)",
    country: "DE",
    timeZone: "DE",
    latitude: "515121N",
    longitude: "0112505E",
  },
  CTA: {
    name: "Catania (Fontanarossa)",
    country: "IT",
    timeZone: "IT",
    latitude: "372800N",
    longitude: "0150350E",
  },
  CUF: {
    name: "Cuneo",
    country: "IT",
    timeZone: "IT",
    latitude: "443251N",
    longitude: "0073723E",
  },
  CWL: {
    name: "Cardiff",
    country: "GB",
    timeZone: "GB",
    latitude: "512348N",
    longitude: "0032036W",
  },
  DBV: {
    name: "Dubrovnik",
    country: "HR",
    timeZone: "HR",
    latitude: "423341N",
    longitude: "0181606E",
  },
  DEB: {
    name: "Debrecen Airport",
    country: "HU",
    timeZone: "HU",
    latitude: "472920N",
    longitude: "0213655E",
  },
  DLE: {
    name: "Dole",
    country: "FR",
    timeZone: "FR",
    latitude: "470234N",
    longitude: "0052606E",
  },
  DLM: {
    name: "Dalaman",
    country: "TR",
    timeZone: "TR",
    latitude: "364247N",
    longitude: "0284733E",
  },
  DNR: {
    name: "Dinard",
    country: "FR",
    timeZone: "FR",
    latitude: "483516N",
    longitude: "0020448W",
  },
  DOL: {
    name: "Deauville-Normandy",
    country: "FR",
    timeZone: "FR",
    latitude: "492148N",
    longitude: "0000936E",
  },
  DRS: {
    name: "Dresden",
    country: "DE",
    timeZone: "DE",
    latitude: "510804N",
    longitude: "0134605E",
  },
  DSA: {
    name: "Doncaster",
    country: "GB",
    timeZone: "GB",
    latitude: "532831N",
    longitude: "0010014W",
  },
  DTM: {
    name: "Dortmund",
    country: "DE",
    timeZone: "DE",
    latitude: "513106N",
    longitude: "0073644E",
  },
  DUB: {
    name: "Dublin ",
    country: "IE",
    timeZone: "IE",
    latitude: "532517N",
    longitude: "0061612W",
  },
  DUS: {
    name: "Düsseldorf",
    country: "DE",
    timeZone: "DE",
    latitude: "511722N",
    longitude: "0064600E",
  },
  EBJ: {
    name: "Esbjerg",
    country: "DK",
    timeZone: "DK",
    latitude: "553135N",
    longitude: "0083309E",
  },
  EBU: {
    name: "St. Etienne",
    country: "FR",
    timeZone: "FR",
    latitude: "453229N",
    longitude: "0041749E",
  },
  EDI: {
    name: "Edinburgh",
    country: "GB",
    timeZone: "GB",
    latitude: "555700N",
    longitude: "0032221W",
  },
  EFL: {
    name: "Kefalonia",
    country: "GR",
    timeZone: "GR",
    latitude: "380712N",
    longitude: "0203002E",
  },
  EGC: {
    name: "Bergerac",
    country: "FR",
    timeZone: "FR",
    latitude: "444928N",
    longitude: "0003114E",
  },
  EIN: {
    name: "Eindhoven",
    country: "NL",
    timeZone: "NL",
    latitude: "512700N",
    longitude: "0052228E",
  },
  EMA: {
    name: "East Midlands",
    country: "GB",
    timeZone: "GB",
    latitude: "524952N",
    longitude: "0011941W",
  },
  ERF: {
    name: "Erfurt",
    country: "DE",
    timeZone: "DE",
    latitude: "505847N",
    longitude: "0105729E",
  },
  ERH: {
    name: "Errachidia Airport",
    country: "MA",
    timeZone: "MA",
    latitude: "315649N",
    longitude: "0042356W",
  },
  ESU: {
    name: "Essaouira",
    country: "MA",
    timeZone: "MA",
    latitude: "312351N",
    longitude: "0094054W",
  },
  ETM: {
    name: "Eilat (Ramon)",
    country: "IL",
    timeZone: "IL",
    latitude: "294338N",
    longitude: "0345954E",
  },
  EVN: {
    name: "Yerevan-Zvartnots Airport",
    country: "AM",
    timeZone: "AM",
    latitude: "400850N",
    longitude: "0442345E",
  },
  EXT: {
    name: "Exeter",
    country: "GB",
    timeZone: "GB",
    latitude: "504404N",
    longitude: "0032450W",
  },
  FAO: {
    name: "Faro",
    country: "PT",
    timeZone: "PT1",
    latitude: "370052N",
    longitude: "0075757W",
  },
  FCO: {
    name: "Rome (Fiumicino) ",
    country: "IT",
    timeZone: "IT",
    latitude: "414801N",
    longitude: "0121420E",
  },
  FDH: {
    name: "Friedrichshafen",
    country: "DE",
    timeZone: "DE",
    latitude: "474017N",
    longitude: "0093041E",
  },
  FEZ: {
    name: "Fez",
    country: "MA",
    timeZone: "MA",
    latitude: "335600N",
    longitude: "0045800W",
  },
  FKB: {
    name: "Karlsruhe (Baden-Baden)",
    country: "DE",
    timeZone: "DE",
    latitude: "484646N",
    longitude: "0080450E",
  },
  FMM: {
    name: "Memmingen",
    country: "DE",
    timeZone: "DE",
    latitude: "475917N",
    longitude: "0101415E",
  },
  FMO: {
    name: "Munster",
    country: "DE",
    timeZone: "DE",
    latitude: "520805N",
    longitude: "0074105E",
  },
  FNC: {
    name: "Madeira",
    country: "PT",
    timeZone: "PT1",
    latitude: "324139N",
    longitude: "0164641W",
  },
  FNI: {
    name: "Nîmes",
    country: "FR",
    timeZone: "FR",
    latitude: "434500N",
    longitude: "0042500E",
  },
  FRA: {
    name: "Frankfurt International",
    country: "DE",
    timeZone: "DE",
    latitude: "500159N",
    longitude: "0083414E",
  },
  FRL: {
    name: "Bologna (Forli)",
    country: "IT",
    timeZone: "IT",
    latitude: "441144N",
    longitude: "0120411E",
  },
  FSC: {
    name: "Figari",
    country: "FR",
    timeZone: "FR",
    latitude: "413008N",
    longitude: "0090548E",
  },
  FUE: {
    name: "Fuerteventura",
    country: "ES",
    timeZone: "ES2",
    latitude: "282709N",
    longitude: "0135149W",
  },
  GDN: {
    name: "Gdańsk",
    country: "PL",
    timeZone: "PL",
    latitude: "542239N",
    longitude: "0182758E",
  },
  GLA: {
    name: "Glasgow ",
    country: "GB",
    timeZone: "GB",
    latitude: "555219N",
    longitude: "0042600W",
  },
  GNB: {
    name: "Grenoble",
    country: "FR",
    timeZone: "FR",
    latitude: "452147N",
    longitude: "0051958E",
  },
  GOA: {
    name: "Genoa",
    country: "IT",
    timeZone: "IT",
    latitude: "442448N",
    longitude: "0085015E",
  },
  GOT: {
    name: "Gottenburg Landvetter",
    country: "SE",
    timeZone: "SE",
    latitude: "574000N",
    longitude: "0121700E",
  },
  GPA: {
    name: "Patras (Araxos)",
    country: "GR",
    timeZone: "GR",
    latitude: "380904N",
    longitude: "0212532E",
  },
  GRO: {
    name: "Girona (Barcelona)",
    country: "ES",
    timeZone: "ES1",
    latitude: "415403N",
    longitude: "0024538E",
  },
  GRQ: {
    name: "Groningen",
    country: "NL",
    timeZone: "NL",
    latitude: "530730N",
    longitude: "0063500E",
  },
  GRX: {
    name: "Granada",
    country: "ES",
    timeZone: "ES1",
    latitude: "371119N",
    longitude: "0034638W",
  },
  GRZ: {
    name: "Graz",
    country: "AT",
    timeZone: "AT",
    latitude: "465937N",
    longitude: "0152624E",
  },
  GSE: {
    name: "Gothenburg (City)",
    country: "SE",
    timeZone: "SE",
    latitude: "574629N",
    longitude: "0115213E",
  },
  GVA: {
    name: "Geneva International Airport",
    country: "CH",
    timeZone: "CH",
    latitude: "461417N",
    longitude: "0060632E",
  },
  HAJ: {
    name: "Hannover",
    country: "DE",
    timeZone: "DE",
    latitude: "522738N",
    longitude: "0094122E",
  },
  HAM: {
    name: "Hamburg",
    country: "DE",
    timeZone: "DE",
    latitude: "533749N",
    longitude: "0095918E",
  },
  HAU: {
    name: "Haugesund",
    country: "NO",
    timeZone: "NO",
    latitude: "592043N",
    longitude: "0051230E",
  },
  HEL: {
    name: "Helsinki",
    country: "FI",
    timeZone: "FI",
    latitude: "601902N",
    longitude: "0245748E",
  },
  HER: {
    name: "Heraklion Crete",
    country: "GR",
    timeZone: "GR",
    latitude: "352023N",
    longitude: "0251049E",
  },
  HHN: {
    name: "Frankfurt (Hahn)",
    country: "DE",
    timeZone: "DE",
    latitude: "495655N",
    longitude: "0071550E",
  },
  HRG: {
    name: "Hurghada Airport",
    country: "EG",
    timeZone: "EG",
    latitude: "271043N",
    longitude: "0334805E",
  },
  HRK: {
    name: "Kharkov",
    country: "UA",
    timeZone: "UA",
    latitude: "495534N",
    longitude: "0361701E",
  },
  HUY: {
    name: "Humberside",
    country: "GB",
    timeZone: "GB",
    latitude: "533428N",
    longitude: "0002103W",
  },
  IAS: {
    name: "Iasi Airport",
    country: "RO",
    timeZone: "RO",
    latitude: "471043N",
    longitude: "0273714E",
  },
  IBZ: {
    name: "Ibiza",
    country: "ES",
    timeZone: "ES1",
    latitude: "385222N",
    longitude: "0012223E",
  },
  IEG: {
    name: "Babimost Airport",
    country: "PL",
    timeZone: "PL",
    latitude: "520819N",
    longitude: "0154755E",
  },
  IEV: {
    name: "Kiev-Zhulhany Airport",
    country: "UA",
    timeZone: "UA",
    latitude: "502406N",
    longitude: "0302659E",
  },
  ILD: {
    name: "Lleida",
    country: "ES",
    timeZone: "ES1",
    latitude: "414341N",
    longitude: "0003207E",
  },
  INI: {
    name: "Nis",
    country: "RS",
    timeZone: "RS",
    latitude: "432014N",
    longitude: "0215113E",
  },
  INN: {
    name: "Innsbruck",
    country: "AT",
    timeZone: "AT",
    latitude: "471537N",
    longitude: "0112038E",
  },
  INV: {
    name: "Inverness",
    country: "GB",
    timeZone: "GB",
    latitude: "573224N",
    longitude: "0040300W",
  },
  JKG: {
    name: "Jonkoping (Axamo)",
    country: "SE",
    timeZone: "SE",
    latitude: "574527N",
    longitude: "0140407E",
  },
  JMK: {
    name: "Mykonos",
    country: "GR",
    timeZone: "GR",
    latitude: "372606N",
    longitude: "0252053E",
  },
  JSI: {
    name: "Skiathos",
    country: "GR",
    timeZone: "GR",
    latitude: "391038N",
    longitude: "0233013E",
  },
  JTR: {
    name: "Santorini",
    country: "GR",
    timeZone: "GR",
    latitude: "362357N",
    longitude: "0252846E",
  },
  KBP: {
    name: "Kyiv - Borispol ",
    country: "UA",
    timeZone: "UA",
    latitude: "502042N",
    longitude: "0305341E",
  },
  KEF: {
    name: "Keflavik International Airport",
    country: "IS",
    timeZone: "IS",
    latitude: "635906N",
    longitude: "0223620W",
  },
  KGS: {
    name: "Kos",
    country: "GR",
    timeZone: "GR",
    latitude: "364736N",
    longitude: "0270530E",
  },
  KHE: {
    name: "Kherson",
    country: "UA",
    timeZone: "UA",
    latitude: "464038N",
    longitude: "0323026E",
  },
  KID: {
    name: "Kristianstad",
    country: "SE",
    timeZone: "SE",
    latitude: "555510N",
    longitude: "0140520E",
  },
  KIR: {
    name: "Kerry",
    country: "IE",
    timeZone: "IE",
    latitude: "521051N",
    longitude: "0093126W",
  },
  KIV: {
    name: "Chisinau Airport",
    country: "MD",
    timeZone: "MD",
    latitude: "465540N",
    longitude: "0285551E",
  },
  KLR: {
    name: "Kalmar",
    country: "SE",
    timeZone: "SE",
    latitude: "564108N",
    longitude: "0161715E",
  },
  KLU: {
    name: "Klagenfurt",
    country: "AT",
    timeZone: "AT",
    latitude: "463834N",
    longitude: "0142016E",
  },
  KLX: {
    name: "Kalamata",
    country: "GR",
    timeZone: "GR",
    latitude: "370406N",
    longitude: "0220132E",
  },
  KRK: {
    name: "Krakow",
    country: "PL",
    timeZone: "PL",
    latitude: "500440N",
    longitude: "0194705E",
  },
  KSC: {
    name: "Kosice",
    country: "SK",
    timeZone: "SK",
    latitude: "483947N",
    longitude: "0211428E",
  },
  KSD: {
    name: "Karlstad",
    country: "SE",
    timeZone: "SE",
    latitude: "592641N",
    longitude: "0132015E",
  },
  KTW: {
    name: "Katowice",
    country: "PL",
    timeZone: "PL",
    latitude: "502900N",
    longitude: "0190500E",
  },
  KUN: {
    name: "Kaunas",
    country: "LT",
    timeZone: "LT",
    latitude: "545750N",
    longitude: "0240505E",
  },
  KUT: {
    name: "Kutaisi",
    country: "GE",
    timeZone: "GE",
    latitude: "421036N",
    longitude: "0422857E",
  },
  KVA: {
    name: "Megas Alexandros",
    country: "GR",
    timeZone: "GR",
    latitude: "405448N",
    longitude: "0243709E",
  },
  LBA: {
    name: "Leeds Bradford",
    country: "GB",
    timeZone: "GB",
    latitude: "535157N",
    longitude: "0013938W",
  },
  LBC: {
    name: "Hamburg (Lübeck)",
    country: "DE",
    timeZone: "DE",
    latitude: "534819N",
    longitude: "0104309E",
  },
  LBG: {
    name: "Le Bourget",
    country: "FR",
    timeZone: "FR",
    latitude: "485810N",
    longitude: "0022629E",
  },
  LCA: {
    name: "Larnaca",
    country: "CY",
    timeZone: "CY",
    latitude: "345230N",
    longitude: "0333729E",
  },
  LCJ: {
    name: "Lodz",
    country: "PL",
    timeZone: "PL",
    latitude: "514319N",
    longitude: "0192353E",
  },
  LDE: {
    name: "Lourdes",
    country: "FR",
    timeZone: "FR",
    latitude: "431055N",
    longitude: "0000013W",
  },
  LDY: {
    name: "Derry",
    country: "GB",
    timeZone: "GB",
    latitude: "550236N",
    longitude: "0070912W",
  },
  LED: {
    name: "St Petersburg",
    country: "RU",
    timeZone: "RU2",
    latitude: "594800N",
    longitude: "0301800E",
  },
  LEI: {
    name: "Almeria",
    country: "ES",
    timeZone: "ES1",
    latitude: "365038N",
    longitude: "0022212W",
  },
  LEJ: {
    name: "Leipzig (Halle)",
    country: "DE",
    timeZone: "DE",
    latitude: "512557N",
    longitude: "0121430E",
  },
  LGG: {
    name: "Liege Airport",
    country: "BE",
    timeZone: "BE",
    latitude: "503815N",
    longitude: "0052636E",
  },
  LGW: {
    name: "London (Gatwick)",
    country: "GB",
    timeZone: "GB",
    latitude: "510853N",
    longitude: "0001125W",
  },
  LIG: {
    name: "Limoges",
    country: "FR",
    timeZone: "FR",
    latitude: "455139N",
    longitude: "0011049E",
  },
  LIL: {
    name: "Lille",
    country: "FR",
    timeZone: "FR",
    latitude: "503348N",
    longitude: "0030513E",
  },
  LIS: {
    name: "Lisbon ",
    country: "PT",
    timeZone: "PT1",
    latitude: "384627N",
    longitude: "0090803W",
  },
  LJU: {
    name: "Brnik Airport",
    country: "SI",
    timeZone: "SI",
    latitude: "461329N",
    longitude: "0142739E",
  },
  LLA: {
    name: "Kallax Airport",
    country: "SE",
    timeZone: "SE",
    latitude: "653238N",
    longitude: "0220719E",
  },
  LNZ: {
    name: "Linz",
    country: "AT",
    timeZone: "AT",
    latitude: "481400N",
    longitude: "0141115E",
  },
  LPA: {
    name: "Gran Canaria",
    country: "ES",
    timeZone: "ES2",
    latitude: "275555N",
    longitude: "0152312W",
  },
  LPL: {
    name: "Liverpool",
    country: "GB",
    timeZone: "GB",
    latitude: "532001N",
    longitude: "0025059W",
  },
  LPP: {
    name: "Lappeenranta",
    country: "FI",
    timeZone: "FI",
    latitude: "610240N",
    longitude: "0280840E",
  },
  LRH: {
    name: "La Rochelle",
    country: "FR",
    timeZone: "FR",
    latitude: "461045N",
    longitude: "0011143W",
  },
  LRT: {
    name: "Lorient",
    country: "FR",
    timeZone: "FR",
    latitude: "474538N",
    longitude: "0032624W",
  },
  LTN: {
    name: "London (Luton)",
    country: "GB",
    timeZone: "GB",
    latitude: "515229N",
    longitude: "0002206W",
  },
  LUX: {
    name: "Luxembourg",
    country: "LU",
    timeZone: "LU",
    latitude: "493724N",
    longitude: "0061216E",
  },
  LUZ: {
    name: "Lublin",
    country: "PL",
    timeZone: "PL",
    latitude: "511353N",
    longitude: "0224126E",
  },
  LWN: {
    name: "Shirak",
    country: "AM",
    timeZone: "AM",
    latitude: "404501N",
    longitude: "0435134E",
  },
  LWO: {
    name: "Lviv",
    country: "UA",
    timeZone: "UA",
    latitude: "494845N",
    longitude: "0235722E",
  },
  LYS: {
    name: "Lyon Satolas",
    country: "FR",
    timeZone: "FR",
    latitude: "454332N",
    longitude: "0050454E",
  },
  MAD: {
    name: "Madrid ",
    country: "ES",
    timeZone: "ES1",
    latitude: "402937N",
    longitude: "0033400W",
  },
  MAH: {
    name: "Mahon",
    country: "ES",
    timeZone: "ES1",
    latitude: "395145N",
    longitude: "0041307E",
  },
  MAN: {
    name: "Manchester ",
    country: "GB",
    timeZone: "GB",
    latitude: "532113N",
    longitude: "0021630W",
  },
  MBX: {
    name: "Maribor",
    country: "SI",
    timeZone: "SI",
    latitude: "462848N",
    longitude: "0154110E",
  },
  MJT: {
    name: "Odysseas Elytis Airport",
    country: "GR",
    timeZone: "GR",
    latitude: "390312N",
    longitude: "0263608E",
  },
  MJV: {
    name: "Murcia",
    country: "ES",
    timeZone: "ES1",
    latitude: "374629N",
    longitude: "0004840W",
  },
  MLA: {
    name: "Malta",
    country: "MT",
    timeZone: "MT",
    latitude: "355114N",
    longitude: "0142859E",
  },
  MME: {
    name: "Teesside Intl.",
    country: "GB",
    timeZone: "GB",
    latitude: "543100N",
    longitude: "0012500W",
  },
  MMX: {
    name: "Malmö",
    country: "SE",
    timeZone: "SE",
    latitude: "553233N",
    longitude: "0132230E",
  },
  MPL: {
    name: "Montpellier",
    country: "FR",
    timeZone: "FR",
    latitude: "433451N",
    longitude: "0035803E",
  },
  MRS: {
    name: "Marseille ",
    country: "FR",
    timeZone: "FR",
    latitude: "432608N",
    longitude: "0051259E",
  },
  MSQ: {
    name: "Minsk International 2 Airport",
    country: "BY",
    timeZone: "BY",
    latitude: "535257N",
    longitude: "0280151E",
  },
  MST: {
    name: "Maastricht",
    country: "NL",
    timeZone: "NL",
    latitude: "505457N",
    longitude: "0054637E",
  },
  MUC: {
    name: "Munich International",
    country: "DE",
    timeZone: "DE",
    latitude: "482114N",
    longitude: "0114710E",
  },
  MXP: {
    name: "Milan Malpensa ",
    country: "IT",
    timeZone: "IT",
    latitude: "453748N",
    longitude: "0084323E",
  },
  NAP: {
    name: "Naples",
    country: "IT",
    timeZone: "IT",
    latitude: "405304N",
    longitude: "0141727E",
  },
  NCE: {
    name: "Nice ",
    country: "FR",
    timeZone: "FR",
    latitude: "433955N",
    longitude: "0071254E",
  },
  NCL: {
    name: "Newcastle",
    country: "GB",
    timeZone: "GB",
    latitude: "550215N",
    longitude: "0014130W",
  },
  NDR: {
    name: "Nador",
    country: "MA",
    timeZone: "MA",
    latitude: "345920N",
    longitude: "0030142W",
  },
  NOC: {
    name: "Knock",
    country: "IE",
    timeZone: "IE",
    latitude: "535437N",
    longitude: "0084907W",
  },
  NQY: {
    name: "Newquay",
    country: "GB",
    timeZone: "GB",
    latitude: "502636N",
    longitude: "0050006W",
  },
  NRK: {
    name: "Norrköping",
    country: "SE",
    timeZone: "SE",
    latitude: "583510N",
    longitude: "0161455E",
  },
  NRN: {
    name: "Düsseldorf (Weeze)",
    country: "DE",
    timeZone: "DE",
    latitude: "513609N",
    longitude: "0060832E",
  },
  NTE: {
    name: "Nantes",
    country: "FR",
    timeZone: "FR",
    latitude: "470930N",
    longitude: "0013635W",
  },
  NUE: {
    name: "Nuremberg",
    country: "DE",
    timeZone: "DE",
    latitude: "492955N",
    longitude: "0110401E",
  },
  NWI: {
    name: "Norwich",
    country: "GB",
    timeZone: "GB",
    latitude: "524100N",
    longitude: "0011700E",
  },
  NYO: {
    name: "Stockholm Skavsta",
    country: "SE",
    timeZone: "SE",
    latitude: "584719N",
    longitude: "0165444E",
  },
  ODS: {
    name: "Odessa-Central",
    country: "UA",
    timeZone: "UA",
    latitude: "462536N",
    longitude: "0304035E",
  },
  OLB: {
    name: "Olbia",
    country: "IT",
    timeZone: "IT",
    latitude: "405355N",
    longitude: "0093104E",
  },
  OMR: {
    name: "Oradea",
    country: "RO",
    timeZone: "RO",
    latitude: "470131N",
    longitude: "0215409E",
  },
  OPO: {
    name: "Porto",
    country: "PT",
    timeZone: "PT1",
    latitude: "411408N",
    longitude: "0084041W",
  },
  ORB: {
    name: "Orebro-Bofors Airport",
    country: "SE",
    timeZone: "SE",
    latitude: "591325N",
    longitude: "0150217E",
  },
  ORK: {
    name: "Cork",
    country: "IE",
    timeZone: "IE",
    latitude: "515029N",
    longitude: "0082928W",
  },
  OSD: {
    name: "Froesoe",
    country: "SE",
    timeZone: "SE",
    latitude: "631140N",
    longitude: "0143001E",
  },
  OSI: {
    name: "Osijek",
    country: "HR",
    timeZone: "HR",
    latitude: "452746N",
    longitude: "0184837E",
  },
  OSL: {
    name: "Oslo",
    country: "NO",
    timeZone: "NO",
    latitude: "601200N",
    longitude: "0110500E",
  },
  OSR: {
    name: "Ostrava",
    country: "CZ",
    timeZone: "CZ",
    latitude: "494146N",
    longitude: "0180640E",
  },
  OST: {
    name: "Ostend",
    country: "BE",
    timeZone: "BE",
    latitude: "511159N",
    longitude: "0025231E",
  },
  OTP: {
    name: "Bucharest (Otopeni)",
    country: "RO",
    timeZone: "RO",
    latitude: "443420N",
    longitude: "0260608E",
  },
  OUD: {
    name: "Oujda",
    country: "MA",
    timeZone: "MA",
    latitude: "344714N",
    longitude: "0015526W",
  },
  OVD: {
    name: "Asturias",
    country: "ES",
    timeZone: "ES1",
    latitude: "433400N",
    longitude: "0060200W",
  },
  OZH: {
    name: "Zaporozhye Airport",
    country: "UA",
    timeZone: "UA",
    latitude: "475201N",
    longitude: "0351856E",
  },
  OZZ: {
    name: "Ouarzazate",
    country: "MA",
    timeZone: "MA",
    latitude: "305621N",
    longitude: "0065434W",
  },
  PAD: {
    name: "Paderborn",
    country: "DE",
    timeZone: "DE",
    latitude: "513651N",
    longitude: "0083659E",
  },
  PDL: {
    name: "Ponta Delgada",
    country: "PT",
    timeZone: "PT2",
    latitude: "374428N",
    longitude: "0254152W",
  },
  PDV: {
    name: "Plovdiv",
    country: "BG",
    timeZone: "BG",
    latitude: "420404N",
    longitude: "0245103E",
  },
  PED: {
    name: "Pardubice",
    country: "CZ",
    timeZone: "CZ",
    latitude: "500048N",
    longitude: "0154419E",
  },
  PEG: {
    name: "Perugia",
    country: "IT",
    timeZone: "IT",
    latitude: "430550N",
    longitude: "0123037E",
  },
  PFO: {
    name: "Paphos",
    country: "CY",
    timeZone: "CY",
    latitude: "344305N",
    longitude: "0322909E",
  },
  PGF: {
    name: "Perpignan",
    country: "FR",
    timeZone: "FR",
    latitude: "424427N",
    longitude: "0025211E",
  },
  PIK: {
    name: "Glasgow (Prestwick)",
    country: "GB",
    timeZone: "GB",
    latitude: "553034N",
    longitude: "0043512W",
  },
  PIS: {
    name: "Poitiers",
    country: "FR",
    timeZone: "FR",
    latitude: "463515N",
    longitude: "0001824E",
  },
  PLQ: {
    name: "Palanga",
    country: "LT",
    timeZone: "LT",
    latitude: "555824N",
    longitude: "0210538E",
  },
  PMF: {
    name: "Parma",
    country: "IT",
    timeZone: "IT",
    latitude: "444920N",
    longitude: "0101743E",
  },
  PMI: {
    name: "Palma Mallorca",
    country: "ES",
    timeZone: "ES1",
    latitude: "393306N",
    longitude: "0024420E",
  },
  PMO: {
    name: "Palermo",
    country: "IT",
    timeZone: "IT",
    latitude: "381055N",
    longitude: "0130558E",
  },
  POZ: {
    name: "Poznań",
    country: "PL",
    timeZone: "PL",
    latitude: "522516N",
    longitude: "0164935E",
  },
  PRG: {
    name: "Prague",
    country: "CZ",
    timeZone: "CZ",
    latitude: "500603N",
    longitude: "0141536E",
  },
  PRN: {
    name: "Pristina",
    country: "RS",
    timeZone: "RS",
    latitude: "423422N",
    longitude: "0210209E",
  },
  PSA: {
    name: "Pisa",
    country: "IT",
    timeZone: "IT",
    latitude: "434058N",
    longitude: "0102344E",
  },
  PSR: {
    name: "Pescara",
    country: "IT",
    timeZone: "IT",
    latitude: "422554N",
    longitude: "0141112E",
  },
  PUF: {
    name: "Pau",
    country: "FR",
    timeZone: "FR",
    latitude: "432248N",
    longitude: "0002507W",
  },
  PUY: {
    name: "Pula",
    country: "HR",
    timeZone: "HR",
    latitude: "445337N",
    longitude: "0135520E",
  },
  PVK: {
    name: "Aktion",
    country: "GR",
    timeZone: "GR",
    latitude: "385532N",
    longitude: "0204555E",
  },
  PXO: {
    name: "Porto Santo Airport",
    country: "PT",
    timeZone: "PT1",
    latitude: "330415N",
    longitude: "0162059W",
  },
  RAK: {
    name: "Marrakesh",
    country: "MA",
    timeZone: "MA",
    latitude: "313625N",
    longitude: "0080211W",
  },
  RBA: {
    name: "Rabat",
    country: "MA",
    timeZone: "MA",
    latitude: "340300N",
    longitude: "0064525W",
  },
  RDZ: {
    name: "Rodez",
    country: "FR",
    timeZone: "FR",
    latitude: "442200N",
    longitude: "0023100E",
  },
  REG: {
    name: "Reggio Calabria",
    country: "IT",
    timeZone: "IT",
    latitude: "381441N",
    longitude: "0153913E",
  },
  REU: {
    name: "Reus (Barcelona)",
    country: "ES",
    timeZone: "ES1",
    latitude: "410900N",
    longitude: "0011010E",
  },
  RHO: {
    name: "Rhodes",
    country: "GR",
    timeZone: "GR",
    latitude: "362420N",
    longitude: "0280510E",
  },
  RIX: {
    name: "Riga",
    country: "LV",
    timeZone: "LV",
    latitude: "565530N",
    longitude: "0235820E",
  },
  RJK: {
    name: "Rijeka",
    country: "HR",
    timeZone: "HR",
    latitude: "451257N",
    longitude: "0143406E",
  },
  RLG: {
    name: "Rostock",
    country: "DE",
    timeZone: "DE",
    latitude: "535505N",
    longitude: "0121642E",
  },
  RMF: {
    name: "Marsa Alam Airport",
    country: "EG",
    timeZone: "EG",
    latitude: "253329N",
    longitude: "0343458E",
  },
  RMI: {
    name: "Rimini",
    country: "IT",
    timeZone: "IT",
    latitude: "440110N",
    longitude: "0123634E",
  },
  RMU: {
    name: "Murcia Intl",
    country: "ES",
    timeZone: "ES1",
    latitude: "374814N",
    longitude: "0010738W",
  },
  RNS: {
    name: "Rennes",
    country: "FR",
    timeZone: "FR",
    latitude: "480407N",
    longitude: "0014353W",
  },
  RVN: {
    name: "Rovaniemi",
    country: "FI",
    timeZone: "FI",
    latitude: "663353N",
    longitude: "0254949E",
  },
  RYG: {
    name: "Oslo (Rygge)",
    country: "NO",
    timeZone: "NO",
    latitude: "592244N",
    longitude: "0104708E",
  },
  RZE: {
    name: "Rzeszów",
    country: "PL",
    timeZone: "PL",
    latitude: "500700N",
    longitude: "0220100E",
  },
  SBZ: {
    name: "Sibiu Airport",
    country: "RO",
    timeZone: "RO",
    latitude: "454708N",
    longitude: "0240529E",
  },
  SCQ: {
    name: "Santiago Comp.",
    country: "ES",
    timeZone: "ES1",
    latitude: "425347N",
    longitude: "0082455W",
  },
  SCV: {
    name: "Suceava Airport",
    country: "RO",
    timeZone: "RO",
    latitude: "474122N",
    longitude: "0262122E",
  },
  SDR: {
    name: "Santander",
    country: "ES",
    timeZone: "ES1",
    latitude: "432537N",
    longitude: "0034912W",
  },
  SEN: {
    name: "Southend",
    country: "GB",
    timeZone: "GB",
    latitude: "513417N",
    longitude: "0004144E",
  },
  SFT: {
    name: "Skelleftea",
    country: "SE",
    timeZone: "SE",
    latitude: "643730N",
    longitude: "0210442E",
  },
  SJJ: {
    name: "Sarajevo Airport",
    country: "BA",
    timeZone: "BA",
    latitude: "434929N",
    longitude: "0181953E",
  },
  SKG: {
    name: "Thessaloniki",
    country: "GR",
    timeZone: "GR",
    latitude: "403111N",
    longitude: "0225815E",
  },
  SNN: {
    name: "Shannon",
    country: "IE",
    timeZone: "IE",
    latitude: "524207N",
    longitude: "0085529W",
  },
  SOB: {
    name: "Balaton",
    country: "HU",
    timeZone: "HU",
    latitude: "464110N",
    longitude: "0170933E",
  },
  SOF: {
    name: "Sofia",
    country: "BG",
    timeZone: "BG",
    latitude: "424142N",
    longitude: "0232430E",
  },
  SPC: {
    name: "La Palma",
    country: "ES",
    timeZone: "ES2",
    latitude: "283735N",
    longitude: "0174520W",
  },
  SPU: {
    name: "Split",
    country: "HR",
    timeZone: "HR",
    latitude: "433130N",
    longitude: "0161732E",
  },
  STN: {
    name: "London (Stansted)",
    country: "GB",
    timeZone: "GB",
    latitude: "515306N",
    longitude: "0001406E",
  },
  STR: {
    name: "Stuttgart",
    country: "DE",
    timeZone: "DE",
    latitude: "484124N",
    longitude: "0091319E",
  },
  SUF: {
    name: "Lamezia",
    country: "IT",
    timeZone: "IT",
    latitude: "385430N",
    longitude: "0161430E",
  },
  SVG: {
    name: "Sola",
    country: "NO",
    timeZone: "NO",
    latitude: "585247N",
    longitude: "0053805E",
  },
  SVQ: {
    name: "Seville",
    country: "ES",
    timeZone: "ES1",
    latitude: "372505N",
    longitude: "0055335W",
  },
  SXB: {
    name: "Strasbourg",
    country: "FR",
    timeZone: "FR",
    latitude: "483231N",
    longitude: "0073804E",
  },
  SXF: {
    name: "Berlin (Schonefeld) ",
    country: "DE",
    timeZone: "DE",
    latitude: "522200N",
    longitude: "0133000E",
  },
  SZG: {
    name: "Salzburg",
    country: "AT",
    timeZone: "AT",
    latitude: "474736N",
    longitude: "0130016E",
  },
  SZY: {
    name: "Olsztyn-Mazury",
    country: "PL",
    timeZone: "PL",
    latitude: "532850N",
    longitude: "0205614E",
  },
  SZZ: {
    name: "Szczecin",
    country: "PL",
    timeZone: "PL",
    latitude: "533500N",
    longitude: "0145400E",
  },
  TAT: {
    name: "Poprad/Tatry Airport",
    country: "SK",
    timeZone: "SK",
    latitude: "490425N",
    longitude: "0201428E",
  },
  TBS: {
    name: "Tbilisi",
    country: "GE",
    timeZone: "GE",
    latitude: "414000N",
    longitude: "0445700E",
  },
  TER: {
    name: "Lajes",
    country: "PT",
    timeZone: "PT2",
    latitude: "384524N",
    longitude: "0270539W",
  },
  TFN: {
    name: "Tenerife (North)",
    country: "ES",
    timeZone: "ES2",
    latitude: "282858N",
    longitude: "0162030W",
  },
  TFS: {
    name: "Tenerife (South)",
    country: "ES",
    timeZone: "ES2",
    latitude: "280240N",
    longitude: "0163421W",
  },
  TGD: {
    name: "Podgorica",
    country: "ME",
    timeZone: "ME",
    latitude: "422130N",
    longitude: "0191507E",
  },
  TGM: {
    name: "Targu Mures",
    country: "RO",
    timeZone: "RO",
    latitude: "462804N",
    longitude: "0242445E",
  },
  TIA: {
    name: "Tirana",
    country: "AL",
    timeZone: "AL",
    latitude: "412454N",
    longitude: "0194315E",
  },
  TIV: {
    name: "Tivat",
    country: "ME",
    timeZone: "ME",
    latitude: "422417N",
    longitude: "0184324E",
  },
  TKU: {
    name: "Turku ",
    country: "FI",
    timeZone: "FI",
    latitude: "603051N",
    longitude: "0221614E",
  },
  TLL: {
    name: "Tallinn",
    country: "EE",
    timeZone: "EE",
    latitude: "592448N",
    longitude: "0244957E",
  },
  TLN: {
    name: "Toulon",
    country: "FR",
    timeZone: "FR",
    latitude: "430600N",
    longitude: "0060900E",
  },
  TLS: {
    name: "Toulouse",
    country: "FR",
    timeZone: "FR",
    latitude: "433749N",
    longitude: "0012154E",
  },
  TLV: {
    name: "Tel Aviv",
    country: "IL",
    timeZone: "IL",
    latitude: "320026N",
    longitude: "0345250E",
  },
  TMP: {
    name: "Tampere",
    country: "FI",
    timeZone: "FI",
    latitude: "612451N",
    longitude: "0233616E",
  },
  TNG: {
    name: "Tangier",
    country: "MA",
    timeZone: "MA",
    latitude: "354300N",
    longitude: "0055500W",
  },
  TNL: {
    name: "Ternopol",
    country: "UA",
    timeZone: "UA",
    latitude: "493400N",
    longitude: "0253600E",
  },
  TPS: {
    name: "Trapani",
    country: "IT",
    timeZone: "IT",
    latitude: "375427N",
    longitude: "0122939E",
  },
  TRF: {
    name: "Oslo (Torp)",
    country: "NO",
    timeZone: "NO",
    latitude: "591112N",
    longitude: "0101531E",
  },
  TRN: {
    name: "Turin",
    country: "IT",
    timeZone: "IT",
    latitude: "451209N",
    longitude: "0073858E",
  },
  TRS: {
    name: "Trieste",
    country: "IT",
    timeZone: "IT",
    latitude: "454939N",
    longitude: "0132820E",
  },
  TSF: {
    name: "Venice (Treviso)",
    country: "IT",
    timeZone: "IT",
    latitude: "453903N",
    longitude: "0121152E",
  },
  TSR: {
    name: "Timisoara",
    country: "RO",
    timeZone: "RO",
    latitude: "454836N",
    longitude: "0212016E",
  },
  TTU: {
    name: "Tetouan",
    country: "MA",
    timeZone: "MA",
    latitude: "353524N",
    longitude: "0051941W",
  },
  TUF: {
    name: "Tours",
    country: "FR",
    timeZone: "FR",
    latitude: "472555N",
    longitude: "0004323E",
  },
  TXL: {
    name: "BerlinTegel",
    country: "DE",
    timeZone: "DE",
    latitude: "523335N",
    longitude: "0131716E",
  },
  TZL: {
    name: "Tuzla",
    country: "BA",
    timeZone: "BA",
    latitude: "442731N",
    longitude: "0184332E",
  },
  VAR: {
    name: "Varna",
    country: "BG",
    timeZone: "BG",
    latitude: "431355N",
    longitude: "0274930E",
  },
  VBS: {
    name: "Verona (Brescia)",
    country: "IT",
    timeZone: "IT",
    latitude: "452544N",
    longitude: "0101950E",
  },
  VBY: {
    name: "Visby Airport",
    country: "SE",
    timeZone: "SE",
    latitude: "573947N",
    longitude: "0182058E",
  },
  VCE: {
    name: "Venice (Marco Polo)",
    country: "IT",
    timeZone: "IT",
    latitude: "453019N",
    longitude: "0122107E",
  },
  VDA: {
    name: "Eilat (Ovda)",
    country: "IL",
    timeZone: "IL",
    latitude: "295625N",
    longitude: "0345609E",
  },
  VGO: {
    name: "Vigo",
    country: "ES",
    timeZone: "ES1",
    latitude: "421335N",
    longitude: "0083740W",
  },
  VIE: {
    name: "Vienna",
    country: "AT",
    timeZone: "AT",
    latitude: "480637N",
    longitude: "0163441E",
  },
  VIT: {
    name: "Vitoria (Bilbao)",
    country: "ES",
    timeZone: "ES1",
    latitude: "425247N",
    longitude: "0024345W",
  },
  VLC: {
    name: "Valencia",
    country: "ES",
    timeZone: "ES1",
    latitude: "392925N",
    longitude: "0002843W",
  },
  VLL: {
    name: "Valladolid",
    country: "ES",
    timeZone: "ES1",
    latitude: "414222N",
    longitude: "0045107W",
  },
  VNO: {
    name: "Vilnius",
    country: "LT",
    timeZone: "LT",
    latitude: "543803N",
    longitude: "0251709E",
  },
  VOL: {
    name: "Volos",
    country: "GR",
    timeZone: "GR",
    latitude: "391311N",
    longitude: "0224740E",
  },
  VRN: {
    name: "Verona",
    country: "IT",
    timeZone: "IT",
    latitude: "452347N",
    longitude: "0105317E",
  },
  VST: {
    name: "Stockholm Vasteras",
    country: "SE",
    timeZone: "SE",
    latitude: "593522N",
    longitude: "0163801E",
  },
  VXO: {
    name: "Smaland (Vaxjo)",
    country: "SE",
    timeZone: "SE",
    latitude: "565600N",
    longitude: "0144400E",
  },
  WAW: {
    name: "Warsaw (Chopin)",
    country: "PL",
    timeZone: "PL",
    latitude: "520957N",
    longitude: "0205802E",
  },
  WMI: {
    name: "Warsaw (Modlin)",
    country: "PL",
    timeZone: "PL",
    latitude: "522704N",
    longitude: "0203906E",
  },
  WRO: {
    name: "Wroclaw",
    country: "PL",
    timeZone: "PL",
    latitude: "510610N",
    longitude: "0165309E",
  },
  XCR: {
    name: "Paris (Vatry)",
    country: "FR",
    timeZone: "FR",
    latitude: "484624N",
    longitude: "0041222E",
  },
  XRY: {
    name: "Jerez",
    country: "ES",
    timeZone: "ES1",
    latitude: "364441N",
    longitude: "0060336W",
  },
  ZAD: {
    name: "Zadar",
    country: "HR",
    timeZone: "HR",
    latitude: "440552N",
    longitude: "0152124E",
  },
  ZAG: {
    name: "Zagreb",
    country: "HR",
    timeZone: "HR",
    latitude: "454435N",
    longitude: "0160413E",
  },
  ZAZ: {
    name: "Zaragoza",
    country: "ES",
    timeZone: "ES1",
    latitude: "413958N",
    longitude: "0010230W",
  },
  ZQW: {
    name: "Zweibrucken",
    country: "DE",
    timeZone: "DE",
    latitude: "491234N",
    longitude: "0072402E",
  },
  ZRH: {
    name: "Zurich",
    country: "CH",
    timeZone: "CH",
    latitude: "472730N",
    longitude: "0083306E",
  },
  ZTH: {
    name: "Zakinthos",
    country: "GR",
    timeZone: "GR",
    latitude: "374503N",
    longitude: "0205303E",
  },
}

export const _easyjetAirports: Record<string, EasyJetAirport> = {
  TIA: {
    name: "Tirana",
    country: "Albania",
    flagUrl: "https://cdn.flightconnections.com/flags/24/AL.png",
    countryCode: "AL",
    latitude: 41.4147,
    longitude: 19.7206,
  },
  INN: {
    name: "Innsbruck",
    country: "Austria",
    flagUrl: "https://cdn.flightconnections.com/flags/24/AT.png",
    countryCode: "AT",
    latitude: 47.2602,
    longitude: 11.344,
  },
  SZG: {
    name: "Salzburg",
    country: "Austria",
    flagUrl: "https://cdn.flightconnections.com/flags/24/AT.png",
    countryCode: "AT",
    latitude: 47.7933,
    longitude: 13.0043,
  },
  BRU: {
    name: "Brussels",
    country: "Belgium",
    flagUrl: "https://cdn.flightconnections.com/flags/24/BE.png",
    countryCode: "BE",
    latitude: 50.9014,
    longitude: 4.48444,
  },
  BOJ: {
    name: "Burgas",
    country: "Bulgaria",
    flagUrl: "https://cdn.flightconnections.com/flags/24/BG.png",
    countryCode: "BG",
    latitude: 42.5696,
    longitude: 27.5152,
  },
  SOF: {
    name: "Sofia",
    country: "Bulgaria",
    flagUrl: "https://cdn.flightconnections.com/flags/24/BG.png",
    countryCode: "BG",
    latitude: 42.6967,
    longitude: 23.4114,
  },
  DBV: {
    name: "Dubrovnik",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 42.5614,
    longitude: 18.2682,
  },
  PUY: {
    name: "Pula",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 44.8935,
    longitude: 13.9222,
  },
  RJK: {
    name: "Rijeka",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 45.2169,
    longitude: 14.5703,
  },
  SPU: {
    name: "Split",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 43.5389,
    longitude: 16.298,
  },
  ZAD: {
    name: "Zadar",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 44.1083,
    longitude: 15.3467,
  },
  LCA: {
    name: "Larnaca",
    country: "Cyprus",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CY.png",
    countryCode: "CY",
    latitude: 34.8751,
    longitude: 33.6249,
  },
  PFO: {
    name: "Paphos",
    country: "Cyprus",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CY.png",
    countryCode: "CY",
    latitude: 34.718,
    longitude: 32.4857,
  },
  PRG: {
    name: "Prague",
    country: "Czechia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CZ.png",
    countryCode: "CZ",
    latitude: 50.1008,
    longitude: 14.26,
  },
  CPH: {
    name: "Copenhagen",
    country: "Denmark",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DK.png",
    countryCode: "DK",
    latitude: 55.6179,
    longitude: 12.656,
  },
  SPX: {
    name: "Giza",
    country: "Egypt",
    flagUrl: "https://cdn.flightconnections.com/flags/24/EG.png",
    countryCode: "EG",
    latitude: 30.1097,
    longitude: 30.8944,
  },
  HRG: {
    name: "Hurghada",
    country: "Egypt",
    flagUrl: "https://cdn.flightconnections.com/flags/24/EG.png",
    countryCode: "EG",
    latitude: 27.1783,
    longitude: 33.7994,
  },
  RMF: {
    name: "Marsa Alam",
    country: "Egypt",
    flagUrl: "https://cdn.flightconnections.com/flags/24/EG.png",
    countryCode: "EG",
    latitude: 25.5571,
    longitude: 34.5837,
  },
  SSH: {
    name: "Sharm el-Sheikh",
    country: "Egypt",
    flagUrl: "https://cdn.flightconnections.com/flags/24/EG.png",
    countryCode: "EG",
    latitude: 27.9773,
    longitude: 34.395,
  },
  KTT: {
    name: "Kittilä",
    country: "Finland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FI.png",
    countryCode: "FI",
    latitude: 67.701,
    longitude: 24.8468,
  },
  RVN: {
    name: "Rovaniemi",
    country: "Finland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FI.png",
    countryCode: "FI",
    latitude: 66.5648,
    longitude: 25.8304,
  },
  AJA: {
    name: "Ajaccio (Corsica)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 41.9236,
    longitude: 8.80292,
  },
  BIA: {
    name: "Bastia (Corsica)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 42.5527,
    longitude: 9.48373,
  },
  BIQ: {
    name: "Biarritz",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.4683,
    longitude: -1.53111,
  },
  BOD: {
    name: "Bordeaux",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 44.8283,
    longitude: -0.715556,
  },
  BES: {
    name: "Brest",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 48.4479,
    longitude: -4.41854,
  },
  CLY: {
    name: "Calvi (Corsica)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 42.5244,
    longitude: 8.79306,
  },
  FSC: {
    name: "Figari",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 41.5006,
    longitude: 9.09778,
  },
  GNB: {
    name: "Grenoble / Lyon",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 45.3629,
    longitude: 5.32937,
  },
  LRH: {
    name: "La Rochelle",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 46.1792,
    longitude: -1.19528,
  },
  LIL: {
    name: "Lille",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 50.5633,
    longitude: 3.08689,
  },
  LIG: {
    name: "Limoges",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 45.8628,
    longitude: 1.17944,
  },
  LDE: {
    name: "Lourdes / Tarbes",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.1787,
    longitude: -0.006439,
  },
  LYS: {
    name: "Lyon",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 45.7256,
    longitude: 5.08111,
  },
  MRS: {
    name: "Marseille",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.4393,
    longitude: 5.22142,
  },
  MPL: {
    name: "Montpellier",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.5762,
    longitude: 3.96301,
  },
  NTE: {
    name: "Nantes",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 47.1532,
    longitude: -1.61073,
  },
  NCE: {
    name: "Nice",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.6584,
    longitude: 7.21587,
  },
  CDG: {
    name: "Paris",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 49.0097,
    longitude: 2.54778,
  },
  BVA: {
    name: "Paris (Beauvais)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 49.0097,
    longitude: 2.54778,
  },
  ORY: {
    name: "Paris (Orly)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 48.7231,
    longitude: 2.35944,
  },
  RNS: {
    name: "Rennes",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 48.0695,
    longitude: -1.73479,
  },
  TLN: {
    name: "Toulon",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.0973,
    longitude: 6.14603,
  },
  TLS: {
    name: "Toulouse",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.6291,
    longitude: 1.36382,
  },
  BER: {
    name: "Berlin",
    country: "Germany",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DE.png",
    countryCode: "DE",
    latitude: 52.3514,
    longitude: 13.4939,
  },
  FDH: {
    name: "Friedrichshafen",
    country: "Germany",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DE.png",
    countryCode: "DE",
    latitude: 47.6713,
    longitude: 9.51149,
  },
  HAM: {
    name: "Hamburg",
    country: "Germany",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DE.png",
    countryCode: "DE",
    latitude: 53.6304,
    longitude: 9.98823,
  },
  MUC: {
    name: "Munich",
    country: "Germany",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DE.png",
    countryCode: "DE",
    latitude: 48.3538,
    longitude: 11.7861,
  },
  GIB: {
    name: "Gibraltar",
    country: "Gibraltar",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GI.png",
    countryCode: "GI",
    latitude: 36.1512,
    longitude: -5.34966,
  },
  ATH: {
    name: "Athens",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 37.9364,
    longitude: 23.9445,
  },
  CHQ: {
    name: "Chania (Crete)",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 35.5317,
    longitude: 24.1497,
  },
  CFU: {
    name: "Corfu (Kerkyra)",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 39.6019,
    longitude: 19.9117,
  },
  HER: {
    name: "Heraklion (Crete)",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 35.3397,
    longitude: 25.1803,
  },
  KLX: {
    name: "Kalamata",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 37.0683,
    longitude: 22.0255,
  },
  EFL: {
    name: "Kefalonia",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 38.1201,
    longitude: 20.5005,
  },
  KGS: {
    name: "Kos",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 36.7933,
    longitude: 27.0917,
  },
  JMK: {
    name: "Mykonos",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 37.4351,
    longitude: 25.3481,
  },
  PVK: {
    name: "Preveza / Lefkada",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 38.9255,
    longitude: 20.7653,
  },
  RHO: {
    name: "Rhodes",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 36.4054,
    longitude: 28.0862,
  },
  JTR: {
    name: "Santorini",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 36.3992,
    longitude: 25.4793,
  },
  JSH: {
    name: "Sitia",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 35.2161,
    longitude: 26.1013,
  },
  JSI: {
    name: "Skiathos",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 39.1771,
    longitude: 23.5037,
  },
  SKG: {
    name: "Thessaloniki",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 40.5197,
    longitude: 22.9709,
  },
  ZTH: {
    name: "Zakynthos Island",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 37.7509,
    longitude: 20.8843,
  },
  BUD: {
    name: "Budapest",
    country: "Hungary",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HU.png",
    countryCode: "HU",
    latitude: 47.4298,
    longitude: 19.2611,
  },
  AEY: {
    name: "Akureyri",
    country: "Iceland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IS.png",
    countryCode: "IS",
    latitude: 65.66,
    longitude: -18.0727,
  },
  KEF: {
    name: "Reykjavik (Keflavik)",
    country: "Iceland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IS.png",
    countryCode: "IS",
    latitude: 63.985,
    longitude: -22.6056,
  },
  IOM: {
    name: "Isle of Man",
    country: "Isle of Man",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IM.png",
    countryCode: "IM",
    latitude: 54.0833,
    longitude: -4.62333,
  },
  TLV: {
    name: "Tel Aviv",
    country: "Israel",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IL.png",
    countryCode: "IL",
    latitude: 32.0114,
    longitude: 34.8867,
  },
  AOI: {
    name: "Ancona",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 43.6163,
    longitude: 13.3623,
  },
  BRI: {
    name: "Bari",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 41.1389,
    longitude: 16.7606,
  },
  BLQ: {
    name: "Bologna",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 44.5354,
    longitude: 11.2887,
  },
  BDS: {
    name: "Brindisi",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 40.6576,
    longitude: 17.947,
  },
  CAG: {
    name: "Cagliari (Sardinia)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 39.2515,
    longitude: 9.05428,
  },
  CTA: {
    name: "Catania",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 37.4668,
    longitude: 15.0664,
  },
  CIY: {
    name: "Comiso",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 36.9946,
    longitude: 14.6072,
  },
  SUF: {
    name: "Lamezia Terme",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 38.9054,
    longitude: 16.2423,
  },
  LMP: {
    name: "Lampedusa",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 35.4979,
    longitude: 12.6181,
  },
  BGY: {
    name: "Milan (Bergamo)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.669,
    longitude: 9.7074,
  },
  LIN: {
    name: "Milan (Linate)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.4494,
    longitude: 9.2783,
  },
  MXP: {
    name: "Milan (Malpensa)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.6306,
    longitude: 8.72811,
  },
  NAP: {
    name: "Naples",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 40.886,
    longitude: 14.2908,
  },
  OLB: {
    name: "Olbia (Sardinia)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 40.8987,
    longitude: 9.51763,
  },
  PMO: {
    name: "Palermo",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 38.176,
    longitude: 13.091,
  },
  PSA: {
    name: "Pisa",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 43.6839,
    longitude: 10.3927,
  },
  FCO: {
    name: "Rome (Fiumicino)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 41.8003,
    longitude: 12.2389,
  },
  QSR: {
    name: "Salerno",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 40.6204,
    longitude: 14.9113,
  },
  TRN: {
    name: "Turin",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.2008,
    longitude: 7.64963,
  },
  VCE: {
    name: "Venice Marco Polo",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.5053,
    longitude: 12.3519,
  },
  VRN: {
    name: "Verona",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.3957,
    longitude: 10.8885,
  },
  JER: {
    name: "Jersey",
    country: "Jersey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/JE.png",
    countryCode: "JE",
    latitude: 49.2081,
    longitude: -2.19528,
  },
  AQJ: {
    name: "Aqaba",
    country: "Jordan",
    flagUrl: "https://cdn.flightconnections.com/flags/24/JO.png",
    countryCode: "JO",
    latitude: 29.6116,
    longitude: 35.0181,
  },
  LUX: {
    name: "Luxembourg City",
    country: "Luxembourg",
    flagUrl: "https://cdn.flightconnections.com/flags/24/LU.png",
    countryCode: "LU",
    latitude: 49.6233,
    longitude: 6.20444,
  },
  MLA: {
    name: "Malta",
    country: "Malta",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MT.png",
    countryCode: "MT",
    latitude: 35.8575,
    longitude: 14.4775,
  },
  TIV: {
    name: "Tivat",
    country: "Montenegro",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ME.png",
    countryCode: "ME",
    latitude: 42.4047,
    longitude: 18.7233,
  },
  AGA: {
    name: "Agadir",
    country: "Morocco",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MA.png",
    countryCode: "MA",
    latitude: 30.325,
    longitude: -9.41307,
  },
  ESU: {
    name: "Essaouira",
    country: "Morocco",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MA.png",
    countryCode: "MA",
    latitude: 31.3975,
    longitude: -9.68167,
  },
  RAK: {
    name: "Marrakech",
    country: "Morocco",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MA.png",
    countryCode: "MA",
    latitude: 31.6069,
    longitude: -8.0363,
  },
  RBA: {
    name: "Rabat",
    country: "Morocco",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MA.png",
    countryCode: "MA",
    latitude: 34.0515,
    longitude: -6.75152,
  },
  AMS: {
    name: "Amsterdam",
    country: "Netherlands",
    flagUrl: "https://cdn.flightconnections.com/flags/24/NL.png",
    countryCode: "NL",
    latitude: 52.3086,
    longitude: 4.76389,
  },
  KRK: {
    name: "Krakow",
    country: "Poland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PL.png",
    countryCode: "PL",
    latitude: 50.0777,
    longitude: 19.7848,
  },
  FAO: {
    name: "Faro",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 37.0144,
    longitude: -7.96591,
  },
  FNC: {
    name: "Funchal (Madeira)",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 32.6979,
    longitude: -16.7745,
  },
  LIS: {
    name: "Lisbon",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 38.7813,
    longitude: -9.13592,
  },
  OPO: {
    name: "Porto",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 41.2356,
    longitude: -8.67806,
  },
  PXO: {
    name: "Porto Santo Island",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 33.0734,
    longitude: -16.35,
  },
  SKP: {
    name: "Skopje",
    country: "Republic of North Macedonia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MK.png",
    countryCode: "MK",
    latitude: 41.9616,
    longitude: 21.6214,
  },
  BEG: {
    name: "Belgrade",
    country: "Serbia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/RS.png",
    countryCode: "RS",
    latitude: 44.8184,
    longitude: 20.3091,
  },
  PRN: {
    name: "Pristina",
    country: "Serbia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/RS.png",
    countryCode: "RS",
    latitude: 42.5746,
    longitude: 21.0295,
  },
  LJU: {
    name: "Ljubljana",
    country: "Slovenia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/SI.png",
    countryCode: "SI",
    latitude: 46.2237,
    longitude: 14.4576,
  },
  LCG: {
    name: "A Coruña",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 43.3021,
    longitude: -8.37726,
  },
  ALC: {
    name: "Alicante",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 38.2822,
    longitude: -0.558156,
  },
  LEI: {
    name: "Almería",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 36.8439,
    longitude: -2.3701,
  },
  BCN: {
    name: "Barcelona",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 41.2971,
    longitude: 2.07846,
  },
  REU: {
    name: "Barcelona Reus (Salou)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 41.1474,
    longitude: 1.16717,
  },
  BIO: {
    name: "Bilbao",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 43.3011,
    longitude: -2.91061,
  },
  FUE: {
    name: "Fuerteventura",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 28.4527,
    longitude: -13.8638,
  },
  LPA: {
    name: "Gran Canaria (Las Palmas)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 27.9319,
    longitude: -15.3866,
  },
  IBZ: {
    name: "Ibiza",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 38.8729,
    longitude: 1.37312,
  },
  ACE: {
    name: "Lanzarote (Arrecife)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 28.9455,
    longitude: -13.6052,
  },
  MAD: {
    name: "Madrid",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 40.4719,
    longitude: -3.56264,
  },
  AGP: {
    name: "Málaga",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 36.6749,
    longitude: -4.49911,
  },
  MAH: {
    name: "Menorca (Mahon)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 39.8626,
    longitude: 4.21865,
  },
  RMU: {
    name: "Murcia",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 37.803,
    longitude: -1.125,
  },
  PMI: {
    name: "Palma de Mallorca",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 39.5517,
    longitude: 2.73881,
  },
  SPC: {
    name: "Santa Cruz de La Palma",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 28.6265,
    longitude: -17.7556,
  },
  SCQ: {
    name: "Santiago de Compostela",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 42.8963,
    longitude: -8.41514,
  },
  SVQ: {
    name: "Seville",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 37.418,
    longitude: -5.89311,
  },
  TFS: {
    name: "Tenerife (Reina Sofía)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 28.0468,
    longitude: -16.5725,
  },
  VLC: {
    name: "Valencia",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 39.4893,
    longitude: -0.481625,
  },
  ARN: {
    name: "Stockholm (Arlanda)",
    country: "Sweden",
    flagUrl: "https://cdn.flightconnections.com/flags/24/SE.png",
    countryCode: "SE",
    latitude: 59.6519,
    longitude: 17.9186,
  },
  BSL: {
    name: "Basel Mulhouse Freiburg",
    country: "Switzerland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CH.png",
    countryCode: "CH",
    latitude: 47.5973,
    longitude: 7.5259,
  },
  GVA: {
    name: "Geneva",
    country: "Switzerland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CH.png",
    countryCode: "CH",
    latitude: 46.2381,
    longitude: 6.10895,
  },
  ZRH: {
    name: "Zürich",
    country: "Switzerland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CH.png",
    countryCode: "CH",
    latitude: 47.4647,
    longitude: 8.54917,
  },
  DJE: {
    name: "Djerba",
    country: "Tunisia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TN.png",
    countryCode: "TN",
    latitude: 33.875,
    longitude: 10.7755,
  },
  NBE: {
    name: "Enfidha",
    country: "Tunisia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TN.png",
    countryCode: "TN",
    latitude: 36.0758,
    longitude: 10.4386,
  },
  AYT: {
    name: "Antalya",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 36.8987,
    longitude: 30.8005,
  },
  BJV: {
    name: "Bodrum",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 37.2506,
    longitude: 27.6643,
  },
  DLM: {
    name: "Dalaman",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 36.7131,
    longitude: 28.7925,
  },
  IST: {
    name: "Istanbul",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 41.2753,
    longitude: 28.7519,
  },
  ADB: {
    name: "Izmir",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 38.292,
    longitude: 27.1489,
  },
  ABZ: {
    name: "Aberdeen",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 57.2019,
    longitude: -2.19778,
  },
  BHD: {
    name: "Belfast City",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 54.6181,
    longitude: -5.8725,
  },
  BFS: {
    name: "Belfast International",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 54.6575,
    longitude: -6.21583,
  },
  BHX: {
    name: "Birmingham",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 52.4539,
    longitude: -1.74803,
  },
  BOH: {
    name: "Bournemouth",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 50.78,
    longitude: -1.8425,
  },
  BRS: {
    name: "Bristol",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.3827,
    longitude: -2.71909,
  },
  EDI: {
    name: "Edinburgh",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 55.95,
    longitude: -3.3725,
  },
  GLA: {
    name: "Glasgow",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 55.8719,
    longitude: -4.43306,
  },
  INV: {
    name: "Inverness",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 57.5425,
    longitude: -4.0475,
  },
  LBA: {
    name: "Leeds / Bradford",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 53.8659,
    longitude: -1.66057,
  },
  LPL: {
    name: "Liverpool",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 53.3336,
    longitude: -2.84972,
  },
  SEN: {
    name: "London (Southend)",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.5703,
    longitude: 0.693333,
  },
  LGW: {
    name: "London Gatwick",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.1481,
    longitude: -0.190278,
  },
  LTN: {
    name: "London Luton",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.8747,
    longitude: -0.368333,
  },
  STN: {
    name: "London Stansted",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.885,
    longitude: 0.235,
  },
  MAN: {
    name: "Manchester",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 53.3537,
    longitude: -2.27495,
  },
  NCL: {
    name: "Newcastle",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 55.0375,
    longitude: -1.69167,
  },
  NQY: {
    name: "Newquay",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 50.4406,
    longitude: -4.99541,
  },
  SOU: {
    name: "Southampton",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 50.9503,
    longitude: -1.3568,
  },
}
