import { type EasyJetAirport } from "."

// SOURCE
// https://colab.research.google.com/drive/1CIYCuBCMTUvzDCQXFaAAYSPqkVexBhPe?usp=sharing
// https://www.flightconnections.com/route-map-easyjet-u2

export const _easyjetAirports: Record<string, EasyJetAirport> = {
  TIA: {
    name: "Tirana",
    country: "Albania",
    flagUrl: "https://cdn.flightconnections.com/flags/24/AL.png",
    countryCode: "AL",
    latitude: 41.4147,
    longitude: 19.7206,
  },
  INN: {
    name: "Innsbruck",
    country: "Austria",
    flagUrl: "https://cdn.flightconnections.com/flags/24/AT.png",
    countryCode: "AT",
    latitude: 47.2602,
    longitude: 11.344,
  },
  SZG: {
    name: "Salzburg",
    country: "Austria",
    flagUrl: "https://cdn.flightconnections.com/flags/24/AT.png",
    countryCode: "AT",
    latitude: 47.7933,
    longitude: 13.0043,
  },
  BRU: {
    name: "Brussels",
    country: "Belgium",
    flagUrl: "https://cdn.flightconnections.com/flags/24/BE.png",
    countryCode: "BE",
    latitude: 50.9014,
    longitude: 4.48444,
  },
  BOJ: {
    name: "Burgas",
    country: "Bulgaria",
    flagUrl: "https://cdn.flightconnections.com/flags/24/BG.png",
    countryCode: "BG",
    latitude: 42.5696,
    longitude: 27.5152,
  },
  SOF: {
    name: "Sofia",
    country: "Bulgaria",
    flagUrl: "https://cdn.flightconnections.com/flags/24/BG.png",
    countryCode: "BG",
    latitude: 42.6967,
    longitude: 23.4114,
  },
  DBV: {
    name: "Dubrovnik",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 42.5614,
    longitude: 18.2682,
  },
  PUY: {
    name: "Pula",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 44.8935,
    longitude: 13.9222,
  },
  RJK: {
    name: "Rijeka",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 45.2169,
    longitude: 14.5703,
  },
  SPU: {
    name: "Split",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 43.5389,
    longitude: 16.298,
  },
  ZAD: {
    name: "Zadar",
    country: "Croatia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HR.png",
    countryCode: "HR",
    latitude: 44.1083,
    longitude: 15.3467,
  },
  LCA: {
    name: "Larnaca",
    country: "Cyprus",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CY.png",
    countryCode: "CY",
    latitude: 34.8751,
    longitude: 33.6249,
  },
  PFO: {
    name: "Paphos",
    country: "Cyprus",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CY.png",
    countryCode: "CY",
    latitude: 34.718,
    longitude: 32.4857,
  },
  PRG: {
    name: "Prague",
    country: "Czechia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CZ.png",
    countryCode: "CZ",
    latitude: 50.1008,
    longitude: 14.26,
  },
  CPH: {
    name: "Copenhagen",
    country: "Denmark",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DK.png",
    countryCode: "DK",
    latitude: 55.6179,
    longitude: 12.656,
  },
  SPX: {
    name: "Giza",
    country: "Egypt",
    flagUrl: "https://cdn.flightconnections.com/flags/24/EG.png",
    countryCode: "EG",
    latitude: 30.1097,
    longitude: 30.8944,
  },
  HRG: {
    name: "Hurghada",
    country: "Egypt",
    flagUrl: "https://cdn.flightconnections.com/flags/24/EG.png",
    countryCode: "EG",
    latitude: 27.1783,
    longitude: 33.7994,
  },
  RMF: {
    name: "Marsa Alam",
    country: "Egypt",
    flagUrl: "https://cdn.flightconnections.com/flags/24/EG.png",
    countryCode: "EG",
    latitude: 25.5571,
    longitude: 34.5837,
  },
  SSH: {
    name: "Sharm el-Sheikh",
    country: "Egypt",
    flagUrl: "https://cdn.flightconnections.com/flags/24/EG.png",
    countryCode: "EG",
    latitude: 27.9773,
    longitude: 34.395,
  },
  KTT: {
    name: "Kittilä",
    country: "Finland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FI.png",
    countryCode: "FI",
    latitude: 67.701,
    longitude: 24.8468,
  },
  RVN: {
    name: "Rovaniemi",
    country: "Finland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FI.png",
    countryCode: "FI",
    latitude: 66.5648,
    longitude: 25.8304,
  },
  AJA: {
    name: "Ajaccio (Corsica)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 41.9236,
    longitude: 8.80292,
  },
  BIA: {
    name: "Bastia (Corsica)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 42.5527,
    longitude: 9.48373,
  },
  BIQ: {
    name: "Biarritz",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.4683,
    longitude: -1.53111,
  },
  BOD: {
    name: "Bordeaux",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 44.8283,
    longitude: -0.715556,
  },
  BES: {
    name: "Brest",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 48.4479,
    longitude: -4.41854,
  },
  CLY: {
    name: "Calvi (Corsica)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 42.5244,
    longitude: 8.79306,
  },
  FSC: {
    name: "Figari",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 41.5006,
    longitude: 9.09778,
  },
  GNB: {
    name: "Grenoble / Lyon",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 45.3629,
    longitude: 5.32937,
  },
  LRH: {
    name: "La Rochelle",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 46.1792,
    longitude: -1.19528,
  },
  LIL: {
    name: "Lille",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 50.5633,
    longitude: 3.08689,
  },
  LIG: {
    name: "Limoges",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 45.8628,
    longitude: 1.17944,
  },
  LDE: {
    name: "Lourdes / Tarbes",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.1787,
    longitude: -0.006439,
  },
  LYS: {
    name: "Lyon",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 45.7256,
    longitude: 5.08111,
  },
  MRS: {
    name: "Marseille",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.4393,
    longitude: 5.22142,
  },
  MPL: {
    name: "Montpellier",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.5762,
    longitude: 3.96301,
  },
  NTE: {
    name: "Nantes",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 47.1532,
    longitude: -1.61073,
  },
  NCE: {
    name: "Nice",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.6584,
    longitude: 7.21587,
  },
  CDG: {
    name: "Paris",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 49.0097,
    longitude: 2.54778,
  },
  BVA: {
    name: "Paris (Beauvais)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 49.0097,
    longitude: 2.54778,
  },
  ORY: {
    name: "Paris (Orly)",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 48.7231,
    longitude: 2.35944,
  },
  RNS: {
    name: "Rennes",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 48.0695,
    longitude: -1.73479,
  },
  TLN: {
    name: "Toulon",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.0973,
    longitude: 6.14603,
  },
  TLS: {
    name: "Toulouse",
    country: "France",
    flagUrl: "https://cdn.flightconnections.com/flags/24/FR.png",
    countryCode: "FR",
    latitude: 43.6291,
    longitude: 1.36382,
  },
  BER: {
    name: "Berlin",
    country: "Germany",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DE.png",
    countryCode: "DE",
    latitude: 52.3514,
    longitude: 13.4939,
  },
  FDH: {
    name: "Friedrichshafen",
    country: "Germany",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DE.png",
    countryCode: "DE",
    latitude: 47.6713,
    longitude: 9.51149,
  },
  HAM: {
    name: "Hamburg",
    country: "Germany",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DE.png",
    countryCode: "DE",
    latitude: 53.6304,
    longitude: 9.98823,
  },
  MUC: {
    name: "Munich",
    country: "Germany",
    flagUrl: "https://cdn.flightconnections.com/flags/24/DE.png",
    countryCode: "DE",
    latitude: 48.3538,
    longitude: 11.7861,
  },
  GIB: {
    name: "Gibraltar",
    country: "Gibraltar",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GI.png",
    countryCode: "GI",
    latitude: 36.1512,
    longitude: -5.34966,
  },
  ATH: {
    name: "Athens",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 37.9364,
    longitude: 23.9445,
  },
  CHQ: {
    name: "Chania (Crete)",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 35.5317,
    longitude: 24.1497,
  },
  CFU: {
    name: "Corfu (Kerkyra)",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 39.6019,
    longitude: 19.9117,
  },
  HER: {
    name: "Heraklion (Crete)",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 35.3397,
    longitude: 25.1803,
  },
  KLX: {
    name: "Kalamata",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 37.0683,
    longitude: 22.0255,
  },
  EFL: {
    name: "Kefalonia",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 38.1201,
    longitude: 20.5005,
  },
  KGS: {
    name: "Kos",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 36.7933,
    longitude: 27.0917,
  },
  JMK: {
    name: "Mykonos",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 37.4351,
    longitude: 25.3481,
  },
  PVK: {
    name: "Preveza / Lefkada",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 38.9255,
    longitude: 20.7653,
  },
  RHO: {
    name: "Rhodes",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 36.4054,
    longitude: 28.0862,
  },
  JTR: {
    name: "Santorini",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 36.3992,
    longitude: 25.4793,
  },
  JSH: {
    name: "Sitia",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 35.2161,
    longitude: 26.1013,
  },
  JSI: {
    name: "Skiathos",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 39.1771,
    longitude: 23.5037,
  },
  SKG: {
    name: "Thessaloniki",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 40.5197,
    longitude: 22.9709,
  },
  ZTH: {
    name: "Zakynthos Island",
    country: "Greece",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GR.png",
    countryCode: "GR",
    latitude: 37.7509,
    longitude: 20.8843,
  },
  BUD: {
    name: "Budapest",
    country: "Hungary",
    flagUrl: "https://cdn.flightconnections.com/flags/24/HU.png",
    countryCode: "HU",
    latitude: 47.4298,
    longitude: 19.2611,
  },
  AEY: {
    name: "Akureyri",
    country: "Iceland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IS.png",
    countryCode: "IS",
    latitude: 65.66,
    longitude: -18.0727,
  },
  KEF: {
    name: "Reykjavik (Keflavik)",
    country: "Iceland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IS.png",
    countryCode: "IS",
    latitude: 63.985,
    longitude: -22.6056,
  },
  IOM: {
    name: "Isle of Man",
    country: "Isle of Man",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IM.png",
    countryCode: "IM",
    latitude: 54.0833,
    longitude: -4.62333,
  },
  TLV: {
    name: "Tel Aviv",
    country: "Israel",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IL.png",
    countryCode: "IL",
    latitude: 32.0114,
    longitude: 34.8867,
  },
  AOI: {
    name: "Ancona",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 43.6163,
    longitude: 13.3623,
  },
  BRI: {
    name: "Bari",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 41.1389,
    longitude: 16.7606,
  },
  BLQ: {
    name: "Bologna",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 44.5354,
    longitude: 11.2887,
  },
  BDS: {
    name: "Brindisi",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 40.6576,
    longitude: 17.947,
  },
  CAG: {
    name: "Cagliari (Sardinia)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 39.2515,
    longitude: 9.05428,
  },
  CTA: {
    name: "Catania",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 37.4668,
    longitude: 15.0664,
  },
  CIY: {
    name: "Comiso",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 36.9946,
    longitude: 14.6072,
  },
  SUF: {
    name: "Lamezia Terme",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 38.9054,
    longitude: 16.2423,
  },
  LMP: {
    name: "Lampedusa",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 35.4979,
    longitude: 12.6181,
  },
  BGY: {
    name: "Milan (Bergamo)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.669,
    longitude: 9.7074,
  },
  LIN: {
    name: "Milan (Linate)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.4494,
    longitude: 9.2783,
  },
  MXP: {
    name: "Milan (Malpensa)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.6306,
    longitude: 8.72811,
  },
  NAP: {
    name: "Naples",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 40.886,
    longitude: 14.2908,
  },
  OLB: {
    name: "Olbia (Sardinia)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 40.8987,
    longitude: 9.51763,
  },
  PMO: {
    name: "Palermo",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 38.176,
    longitude: 13.091,
  },
  PSA: {
    name: "Pisa",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 43.6839,
    longitude: 10.3927,
  },
  FCO: {
    name: "Rome (Fiumicino)",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 41.8003,
    longitude: 12.2389,
  },
  QSR: {
    name: "Salerno",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 40.6204,
    longitude: 14.9113,
  },
  TRN: {
    name: "Turin",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.2008,
    longitude: 7.64963,
  },
  VCE: {
    name: "Venice Marco Polo",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.5053,
    longitude: 12.3519,
  },
  VRN: {
    name: "Verona",
    country: "Italy",
    flagUrl: "https://cdn.flightconnections.com/flags/24/IT.png",
    countryCode: "IT",
    latitude: 45.3957,
    longitude: 10.8885,
  },
  JER: {
    name: "Jersey",
    country: "Jersey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/JE.png",
    countryCode: "JE",
    latitude: 49.2081,
    longitude: -2.19528,
  },
  AQJ: {
    name: "Aqaba",
    country: "Jordan",
    flagUrl: "https://cdn.flightconnections.com/flags/24/JO.png",
    countryCode: "JO",
    latitude: 29.6116,
    longitude: 35.0181,
  },
  LUX: {
    name: "Luxembourg City",
    country: "Luxembourg",
    flagUrl: "https://cdn.flightconnections.com/flags/24/LU.png",
    countryCode: "LU",
    latitude: 49.6233,
    longitude: 6.20444,
  },
  MLA: {
    name: "Malta",
    country: "Malta",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MT.png",
    countryCode: "MT",
    latitude: 35.8575,
    longitude: 14.4775,
  },
  TIV: {
    name: "Tivat",
    country: "Montenegro",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ME.png",
    countryCode: "ME",
    latitude: 42.4047,
    longitude: 18.7233,
  },
  AGA: {
    name: "Agadir",
    country: "Morocco",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MA.png",
    countryCode: "MA",
    latitude: 30.325,
    longitude: -9.41307,
  },
  ESU: {
    name: "Essaouira",
    country: "Morocco",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MA.png",
    countryCode: "MA",
    latitude: 31.3975,
    longitude: -9.68167,
  },
  RAK: {
    name: "Marrakech",
    country: "Morocco",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MA.png",
    countryCode: "MA",
    latitude: 31.6069,
    longitude: -8.0363,
  },
  RBA: {
    name: "Rabat",
    country: "Morocco",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MA.png",
    countryCode: "MA",
    latitude: 34.0515,
    longitude: -6.75152,
  },
  AMS: {
    name: "Amsterdam",
    country: "Netherlands",
    flagUrl: "https://cdn.flightconnections.com/flags/24/NL.png",
    countryCode: "NL",
    latitude: 52.3086,
    longitude: 4.76389,
  },
  KRK: {
    name: "Krakow",
    country: "Poland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PL.png",
    countryCode: "PL",
    latitude: 50.0777,
    longitude: 19.7848,
  },
  FAO: {
    name: "Faro",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 37.0144,
    longitude: -7.96591,
  },
  FNC: {
    name: "Funchal (Madeira)",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 32.6979,
    longitude: -16.7745,
  },
  LIS: {
    name: "Lisbon",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 38.7813,
    longitude: -9.13592,
  },
  OPO: {
    name: "Porto",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 41.2356,
    longitude: -8.67806,
  },
  PXO: {
    name: "Porto Santo Island",
    country: "Portugal",
    flagUrl: "https://cdn.flightconnections.com/flags/24/PT.png",
    countryCode: "PT",
    latitude: 33.0734,
    longitude: -16.35,
  },
  SKP: {
    name: "Skopje",
    country: "Republic of North Macedonia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/MK.png",
    countryCode: "MK",
    latitude: 41.9616,
    longitude: 21.6214,
  },
  BEG: {
    name: "Belgrade",
    country: "Serbia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/RS.png",
    countryCode: "RS",
    latitude: 44.8184,
    longitude: 20.3091,
  },
  PRN: {
    name: "Pristina",
    country: "Serbia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/RS.png",
    countryCode: "RS",
    latitude: 42.5746,
    longitude: 21.0295,
  },
  LJU: {
    name: "Ljubljana",
    country: "Slovenia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/SI.png",
    countryCode: "SI",
    latitude: 46.2237,
    longitude: 14.4576,
  },
  LCG: {
    name: "A Coruña",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 43.3021,
    longitude: -8.37726,
  },
  ALC: {
    name: "Alicante",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 38.2822,
    longitude: -0.558156,
  },
  LEI: {
    name: "Almería",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 36.8439,
    longitude: -2.3701,
  },
  BCN: {
    name: "Barcelona",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 41.2971,
    longitude: 2.07846,
  },
  REU: {
    name: "Barcelona Reus (Salou)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 41.1474,
    longitude: 1.16717,
  },
  BIO: {
    name: "Bilbao",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 43.3011,
    longitude: -2.91061,
  },
  FUE: {
    name: "Fuerteventura",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 28.4527,
    longitude: -13.8638,
  },
  LPA: {
    name: "Gran Canaria (Las Palmas)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 27.9319,
    longitude: -15.3866,
  },
  IBZ: {
    name: "Ibiza",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 38.8729,
    longitude: 1.37312,
  },
  ACE: {
    name: "Lanzarote (Arrecife)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 28.9455,
    longitude: -13.6052,
  },
  MAD: {
    name: "Madrid",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 40.4719,
    longitude: -3.56264,
  },
  AGP: {
    name: "Málaga",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 36.6749,
    longitude: -4.49911,
  },
  MAH: {
    name: "Menorca (Mahon)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 39.8626,
    longitude: 4.21865,
  },
  RMU: {
    name: "Murcia",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 37.803,
    longitude: -1.125,
  },
  PMI: {
    name: "Palma de Mallorca",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 39.5517,
    longitude: 2.73881,
  },
  SPC: {
    name: "Santa Cruz de La Palma",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 28.6265,
    longitude: -17.7556,
  },
  SCQ: {
    name: "Santiago de Compostela",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 42.8963,
    longitude: -8.41514,
  },
  SVQ: {
    name: "Seville",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 37.418,
    longitude: -5.89311,
  },
  TFS: {
    name: "Tenerife (Reina Sofía)",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 28.0468,
    longitude: -16.5725,
  },
  VLC: {
    name: "Valencia",
    country: "Spain",
    flagUrl: "https://cdn.flightconnections.com/flags/24/ES.png",
    countryCode: "ES",
    latitude: 39.4893,
    longitude: -0.481625,
  },
  ARN: {
    name: "Stockholm (Arlanda)",
    country: "Sweden",
    flagUrl: "https://cdn.flightconnections.com/flags/24/SE.png",
    countryCode: "SE",
    latitude: 59.6519,
    longitude: 17.9186,
  },
  BSL: {
    name: "Basel Mulhouse Freiburg",
    country: "Switzerland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CH.png",
    countryCode: "CH",
    latitude: 47.5973,
    longitude: 7.5259,
  },
  GVA: {
    name: "Geneva",
    country: "Switzerland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CH.png",
    countryCode: "CH",
    latitude: 46.2381,
    longitude: 6.10895,
  },
  ZRH: {
    name: "Zürich",
    country: "Switzerland",
    flagUrl: "https://cdn.flightconnections.com/flags/24/CH.png",
    countryCode: "CH",
    latitude: 47.4647,
    longitude: 8.54917,
  },
  DJE: {
    name: "Djerba",
    country: "Tunisia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TN.png",
    countryCode: "TN",
    latitude: 33.875,
    longitude: 10.7755,
  },
  NBE: {
    name: "Enfidha",
    country: "Tunisia",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TN.png",
    countryCode: "TN",
    latitude: 36.0758,
    longitude: 10.4386,
  },
  AYT: {
    name: "Antalya",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 36.8987,
    longitude: 30.8005,
  },
  BJV: {
    name: "Bodrum",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 37.2506,
    longitude: 27.6643,
  },
  DLM: {
    name: "Dalaman",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 36.7131,
    longitude: 28.7925,
  },
  IST: {
    name: "Istanbul",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 41.2753,
    longitude: 28.7519,
  },
  ADB: {
    name: "Izmir",
    country: "Turkey",
    flagUrl: "https://cdn.flightconnections.com/flags/24/TR.png",
    countryCode: "TR",
    latitude: 38.292,
    longitude: 27.1489,
  },
  ABZ: {
    name: "Aberdeen",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 57.2019,
    longitude: -2.19778,
  },
  BHD: {
    name: "Belfast City",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 54.6181,
    longitude: -5.8725,
  },
  BFS: {
    name: "Belfast International",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 54.6575,
    longitude: -6.21583,
  },
  BHX: {
    name: "Birmingham",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 52.4539,
    longitude: -1.74803,
  },
  BOH: {
    name: "Bournemouth",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 50.78,
    longitude: -1.8425,
  },
  BRS: {
    name: "Bristol",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.3827,
    longitude: -2.71909,
  },
  EDI: {
    name: "Edinburgh",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 55.95,
    longitude: -3.3725,
  },
  GLA: {
    name: "Glasgow",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 55.8719,
    longitude: -4.43306,
  },
  INV: {
    name: "Inverness",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 57.5425,
    longitude: -4.0475,
  },
  LBA: {
    name: "Leeds / Bradford",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 53.8659,
    longitude: -1.66057,
  },
  LPL: {
    name: "Liverpool",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 53.3336,
    longitude: -2.84972,
  },
  SEN: {
    name: "London (Southend)",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.5703,
    longitude: 0.693333,
  },
  LGW: {
    name: "London Gatwick",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.1481,
    longitude: -0.190278,
  },
  LTN: {
    name: "London Luton",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.8747,
    longitude: -0.368333,
  },
  STN: {
    name: "London Stansted",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 51.885,
    longitude: 0.235,
  },
  MAN: {
    name: "Manchester",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 53.3537,
    longitude: -2.27495,
  },
  NCL: {
    name: "Newcastle",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 55.0375,
    longitude: -1.69167,
  },
  NQY: {
    name: "Newquay",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 50.4406,
    longitude: -4.99541,
  },
  SOU: {
    name: "Southampton",
    country: "United Kingdom",
    flagUrl: "https://cdn.flightconnections.com/flags/24/GB.png",
    countryCode: "GB",
    latitude: 50.9503,
    longitude: -1.3568,
  },
}
